version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      DK6Wgw5lNrJ0yE7QTK6exbFGCMoUkQYMYuERsgQqyO2NZ/8Q3YbnmmpCX1ughoSGF115nMDBd+A3BYcafPO2Y8E8xtCn8+pK8Z25aUi77AtTdrIp9o+kmFCNfpKOBeMr/zGGiYB/azwkIA2lo331GdBPrdbLd0qLWFbVKWoqoog=
