# v1.3.8 November 7, 2013
# https://github.com/bevry/base
language: node_js
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travisci@bevry.me